# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.define "kube-01" do |kube|
    kube.vm.hostname = "kube-01"
    kube.vm.network "private_network", ip: "192.168.56.101"
    kube.vm.provider :virtualbox do |vb|
       vb.memory = 2048
       vb.cpus = 2
    end  
    kube.vm.provision "shell", inline: $script
  end
 
 config.vm.define "kube-02" do |kube|
    kube.vm.hostname = "kube-02"
    kube.vm.network "private_network", ip: "192.168.56.102"
    kube.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", 2048]
       vb.customize ["modifyvm", :id, "--cpus", 1]
    end
    kube.vm.provision "shell", inline: $script
  end

 config.vm.define "kube-03" do |kube|
    kube.vm.hostname = "kube-03"
    kube.vm.network "private_network", ip: "192.168.56.103"
    kube.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", 2048]
       vb.customize ["modifyvm", :id, "--cpus", 1]
    end
    kube.vm.provision "shell", inline: $script
  end

$script = <<SCRIPT
echo I am provisioning...
cp /vagrant/hosts /etc/hosts
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
cp /vagrant/kubernetes.list /etc/apt/sources.list.d/kubernetes.list
apt-get update 
apt-get install -y docker.io kubelet kubeadm kubectl kubernetes-cni
rm -rf /var/lib/kubelet/*
echo I am turning off swap...
swapoff -a
echo I am joining NFS...
apt-get install nfs-common -y
SCRIPT

end
